### ISSUE TITLE
Transferring rollup-plugin-unassert

### ISSUE THREAD

**Issue by mourner** [unassert-js/unassert#14]
Hi @twada!

I'm taking on the maintenance of `rollup-plugin-unassert` by @IvanSanchez, which was previously [hosted on GitLab](https://gitlab.com/IvanSanchez/rollup-plugin-unassert/). I coordinated the move to GitHub with Ivan and it's now temporarily [hosted here](https://github.com/mourner/rollup-plugin-unassert), but I'd love to transfer it to the `unassert-js` organization since it hosts all other unassert plugins. Would you mind giving me collaborator permissions to do so?

Thank you!

**Comment by twada** [comment]
@mourner Oh great! I'd love to invite you as a member of `unassert-js` organization!
I just invited you so would you check your mailbox?

Thanks!

**Comment by mourner** [comment]
Got it, thank you! https://github.com/unassert-js/rollup-plugin-unassert

**Comment by mourner** [comment]
@twada one more thing —  can you please enable Travis integration for the repo?

**Comment by twada** [comment]
@mourner Ah nice catch! I've just activated travis integration for `rollup-plugin-unassert`.
