### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by RebeccaStevens** [unassert-js/unassert#23]
Can we get a new release with the latest dependency updates?

**Comment by twada** [comment]
@RebeccaStevens Thank you for your comment. I'll cut a new release in next month.

**Comment by RebeccaStevens** [comment]
@twada Any update on this?

**Comment by twada** [comment]
FYI: unassert v2.0.0 is published.
https://github.com/unassert-js/unassert/blob/master/CHANGELOG.md#200-2022-08-01
